name: Build REST Regression

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/rest_reg.yml
      - recipe_rest_reg/**

jobs:
  build-rest-regression:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: build-env
          # python-version: 3.11
          environment-file: recipe_rest_reg/env.yaml
          # use-mamba: true
      - name: Build REST Regression recipe
        run: |
          # conda info
          # conda env list
          conda activate build-env
          conda-build recipe_rest_reg --output-folder output -c conda-forge 
          # conda-build --test output/*/*tar.bz2
      - name: Upload to Anaconda.org
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA }}
        run: |
          anaconda -t $ANACONDA_API_TOKEN upload ./output/*/*.tar.bz2 --skip-existing
          