name: Build REST Regression

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/rest_reg.yml
      - recipe_rest_reg/**

jobs:
  build-rest-regression:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: build-env
          # python-version: 3.11
          environment-file: env_rattler.yaml
          # use-mamba: true
      - name: Cache Cargo dependencies and build output
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ runner.os }}-cargo-${{ hashFiles('output/bld/rattler-build_rest_regression/work/rest_regression/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Extract Git source info for cache key
        id: get-git-key
        shell: bash
        run: |
          # This uses yq (a YAML processor) to read the git URL and tag from recipe.yaml
          # Install yq if not present. With Conda, you can add 'yq' to your environment.yml.
          # This example assumes a simple recipe structure. You may need to adjust the yq query.
          GIT_URL=$(yq eval '.source.git.url' ./recipe.yaml)
          GIT_TAG=$(yq eval '.source.git.tag' ./recipe.yaml)

          # Combine and hash them to create a stable, shorter key component
          export GIT_SOURCE_HASH=$(echo -n "${GIT_URL}-${GIT_TAG}" | sha256sum | head -c 12)
      - name: Cache Rattler git sources
        uses: actions/cache@v4
        with:
          path: |
            # output/bld/rattler-build_rest_regression
            output/src_cache/
          key: ${{ runner.os }}-git-src-${{ env.GIT_SOURCE_HASH }}
      - name: Build REST Regression recipe
        run: |
          # conda info
          # conda env list
          conda activate build-env
          rattler-build build --recipe recipe_rest_reg --no-build-id --output-dir output -c conda-forge
      - name: Upload to Anaconda.org
        env:
          ANACONDA_API_KEY: ${{ secrets.ANACONDA }}
        run: |
          rattler-build upload anaconda -o restgroup ./output/*/*.conda
